import {React, useState } from 'react';
import './Gallery.scss';
import { useEffect } from 'react';
import {Collection} from './Collection.jsx';

export const Gallery = () =>{
    const cats = [
        { "name": "всё"},
        { "name": "арабы топ)"},
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },
        { "name": "..." },



    ]


const [categoryId, setCategoryId] = useState(0);
const [collection, setCollections] = useState([]); 
const [searchValue, setSearchValue ] = useState('');
useEffect(()=>{
    fetch(`https://63708fe208218c267e017d80.mockapi.io/Arr?${
        categoryId ? `category=${categoryId}` : '' }`,
        console.log(categoryId)
    )
    .then((res)=> res.json())
    .then((json) => {
        setCollections(json);
       
    })
    .catch((err)=>{
        console.warn(err);
     
        alert('ошибка')
    });
}, [categoryId]);

return (
  <div className="Gallery">
    <h1>interesные картинкi</h1>
    <div className="top">

 <ul className="tags">
       {cats.map((obj, i)=>(
          <li
          onClick = {()=> setCategoryId(i)}
          className={categoryId===i? 'active':''}
          key = {obj.name}>
              {obj.name}
          </li>
       ))}
      </ul> 



    
      <input value = {searchValue}                        //!!
       onChange={e => setSearchValue(e.target.value)} 
       className="search-input" 
       placeholder="поиск по названию" 
       />

    </div>
    <div className="content">


    {collection                                                                 //!!
      .filter((obj)=> obj.name.toLowerCase().includes(searchValue.toLowerCase()))
      .map((obj, index)=>(
          <Collection key ={index} name ={obj.name} images = {obj.photos}/>
      ))}



    </div>
  </div>
);
}


